server:
  port: 18087
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  # 解决feign name重复问题
  main:
    allow-bean-definition-overriding: true
# 生成静态页的位置
pagepath: D:\software\code\changgou-parent\changgou-web\changgou-web-item\src\main\resources\templates\items